version: "3.9"

services:
  provenance:
    build: .
    environment:
      PROVENANCE_REDIS_URL: redis://redis:6379/0
      PROVENANCE_SERVICE_BASE_URL: http://localhost:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
