name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  UV_LINK_MODE: copy

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm lint
        run: make helm-lint

      - name: Helm template (defaults)
        run: make helm-template

      - name: Helm template (external Redis)
        run: >
          helm template provenance charts/provenance
          --set redis.enabled=false
          --set env.PROVENANCE_REDIS_URL='redis://external-redis:6379/0'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Sync dependencies
        run: uv sync --extra dev --extra dashboard --extra warehouse --extra client

      - name: Run tests
        run: uv run -- pytest

      - name: Streamlit smoke
        run: uv run -- python -m py_compile dashboards/agent_dashboard.py
